import type { State } from './types';

// Curated looks. Each one is a whole composition — environment, material, post
// and framing tuned together, because none of these references is a material
// setting. Picking a look stamps every field, and every field stays
// individually adjustable after.
//
// ORDER MATTERS: the first three are Joonas's own, dialled in by hand and then
// read back off the panel. Everything after is derived from the reference
// frames. The bar renders in this order, so the hand-made ones lead.

export interface Look {
  name: string;
  note: string;
  set: Partial<State>;
}

export const LOOKS: Look[] = [
  // ── Joonas's, hand-tuned ──────────────────────────────────────────────────
  {
    // Everything that scatters or splits is at zero — dispersion 0, thickness 0,
    // roughness 0 — so the body is pure undistorted glass and the Max reads
    // dead straight through it. The only movement is the thickness loop
    // breathing 0 → 4 → 0, which is what keeps it from looking like a still.
    name: 'clean',
    note: 'pure undistorted glass — nothing splits, nothing scatters',
    set: {
      subject: 'pill',
      env: 'darkroom',
      shell: 'glass',
      fill: 'empty',
      motion: 'float',
      speed: 1,
      dispersion: 0,
      thickness: 0,
      ior: 1.52,
      roughness: 0,
      aspect: 115.2 / 53.31,
      cloud: 0,
      bloom: 0.25,
      exposure: 1.0,
      hue: 1.0,
      spread: 1.0,
      glow: 1.05,
      label: true,
      zoom: 0.62,
      displace: 0.03,
      textDepth: 0.01,
      textBevel: 0,
      dof: false,
      dofFocus: 1,
      dofAperture: 0.5,
      revealStyle: 'thick',
      revealSpeed: 0.5,
      revealLoop: true,
      thickLoop: true,
      thickLoopMax: 4,
      clipAxis: 'yaw',
      clipAngle: 45,
      clipDur: 4,
      clipLoop: true,
    },
  },
  {
    name: 'sky max',
    note: 'the floating capsule — clear glass, deep blue, cumulus low in frame',
    // reveal: the Max sits fixed behind 4.0 of glass and resolves as it thins
    set: {
      env: 'sky',
      shell: 'glass',
      fill: 'empty',
      motion: 'float',
      speed: 1,
      dispersion: 3.4,
      thickness: 0,
      ior: 1.47,
      roughness: 0.02,
      aspect: 115.2 / 53.31,
      cloud: 1,
      bloom: 0.42,
      exposure: 0.82,
      label: true,
      zoom: 1,
      displace: 0,
      dof: false,
      dofFocus: 1,
      dofAperture: 0.6,
      revealStyle: 'thick',
    },
  },
  {
    // An IOR of exactly 1.0 is the trick: the ray is not bent at all, so the
    // transmissive body stops behaving like glass and reads as a soft solid.
    // Roughness 0.8 gives the matte skin, and the label survives as a shallow
    // deboss instead of a highlight.
    name: 'soap',
    note: 'matte white body, no refraction — the Max sinks in as a deboss',
    set: {
      env: 'soft',
      shell: 'frosted',
      fill: 'empty',
      motion: 'turntable',
      speed: 1,
      dispersion: 2.6,
      thickness: 2.4,
      ior: 1.0,
      roughness: 0.8,
      aspect: 1.87,
      cloud: 1.6,
      bloom: 0.56,
      exposure: 0.78,
      label: true,
      zoom: 1,
      displace: 0,
      dof: false,
      dofFocus: 1,
      dofAperture: 0.6,
    },
  },
  // ── glass, from the reference frames ──────────────────────────────────────
  {
    // Thickness is what kills a rainbow — a thick slab averages the three
    // channel paths back toward white, so the fringe only survives on a shallow
    // one. Paired with the hard-edged studio softboxes, which give the edges
    // something with real contrast to split.
    name: 'prism',
    note: 'thin hard glass on a studio sweep — the rainbow lives on the edge',
    set: {
      env: 'studio',
      shell: 'prism',
      fill: 'empty',
      motion: 'turntable',
      speed: 0.42,
      dispersion: 9,
      thickness: 0.3,
      ior: 1.66,
      roughness: 0,
      aspect: 115.2 / 53.31,
      cloud: 0,
      bloom: 0.16,
      exposure: 0.72,
      label: true,
      zoom: 1.2,
      displace: 0,
      dof: false,
      dofFocus: 1,
      dofAperture: 0.4,
    },
  },
  {
    name: 'molten',
    note: 'heavy clear glass over cold mist — the silhouette itself bulges',
    set: {
      env: 'mist',
      shell: 'molten',
      fill: 'empty',
      motion: 'float',
      speed: 0.5,
      dispersion: 2.2,
      thickness: 1.9,
      ior: 1.52,
      roughness: 0,
      aspect: 2.0,
      cloud: 1,
      bloom: 0.2,
      exposure: 0.8,
      label: false,
      zoom: 1.05,
      displace: 0.085,
      dof: true,
      dofFocus: 1,
      dofAperture: 0.9,
    },
  },
  {
    // Roughness on a TRANSMISSIVE material scatters the ray on its way through,
    // which frosts what you see behind the body rather than merely dulling the
    // reflection off it. That is a different blur from depth of field, and
    // running both is what gives the soft, milky-glass read.
    name: 'frost',
    note: 'blurred glass — the scatter is inside the body, not on the lens',
    set: {
      env: 'soft',
      shell: 'frosted',
      fill: 'empty',
      motion: 'float',
      speed: 0.5,
      dispersion: 1.4,
      thickness: 1.5,
      ior: 1.42,
      roughness: 0.34,
      aspect: 115.2 / 53.31,
      cloud: 0,
      bloom: 0.2,
      exposure: 0.8,
      label: true,
      zoom: 1.05,
      displace: 0.02,
      dof: true,
      dofFocus: 1,
      dofAperture: 1.1,
    },
  },
  {
    // Wide open and focused slightly behind the object, so the near cap goes
    // soft while the far one stays sharp. That mismatch across a single body is
    // what makes a render read as photographed rather than rendered.
    name: 'haze',
    note: 'shallow focus across the body — near cap soft, far cap sharp',
    set: {
      env: 'sky',
      shell: 'glass',
      fill: 'empty',
      motion: 'float',
      speed: 0.36,
      dispersion: 5.2,
      thickness: 0,
      ior: 1.5,
      roughness: 0.06,
      aspect: 115.2 / 53.31,
      cloud: 1.25,
      bloom: 0.5,
      exposure: 0.74,
      label: true,
      zoom: 1.3,
      displace: 0,
      dof: true,
      dofFocus: 1.06,
      dofAperture: 2.1,
    },
  },
  {
    name: 'dusk',
    note: 'low sun through the body — warm one side, violet the other',
    set: {
      env: 'dusk',
      shell: 'glass',
      fill: 'empty',
      motion: 'float',
      speed: 0.7,
      dispersion: 5.5,
      thickness: 0,
      ior: 1.5,
      roughness: 0.015,
      aspect: 115.2 / 53.31,
      cloud: 1,
      bloom: 0.6,
      exposure: 0.7,
      label: true,
      zoom: 1.05,
      displace: 0,
      dof: true,
      dofFocus: 1,
      dofAperture: 0.7,
    },
  },
  {
    name: 'spectrum',
    note: 'soft holographic body — a full spectrum wrapped over the form',
    set: {
      env: 'soft',
      shell: 'spectral',
      fill: 'empty',
      motion: 'float',
      speed: 0.4,
      roughness: 0.42,
      aspect: 2.0,
      cloud: 0,
      bloom: 0.35,
      exposure: 0.92,
      hue: 0.58,
      spread: 1.0,
      glow: 1.05,
      label: false,
      zoom: 1.15,
      displace: 0,
      dof: false,
      dofFocus: 1,
      dofAperture: 0.5,
    },
  },
  {
    name: 'oil slick',
    note: 'thin-film iridescence on black — colour only where light rakes it',
    set: {
      env: 'noir',
      shell: 'oil',
      fill: 'empty',
      motion: 'float',
      speed: 0.34,
      dispersion: 4.5,
      thickness: 0.55,
      ior: 1.58,
      roughness: 0.02,
      aspect: 2.4,
      cloud: 0,
      bloom: 0.7,
      exposure: 1.05,
      label: false,
      zoom: 1.15,
      displace: 0,
      dof: true,
      dofFocus: 1,
      dofAperture: 0.8,
    },
  },
  {
    name: 'golden hour',
    note: 'sun on the horizon — one blazing edge, everything else falls away',
    set: {
      env: 'golden',
      shell: 'glass',
      fill: 'empty',
      motion: 'float',
      speed: 0.42,
      dispersion: 6.5,
      thickness: 0,
      ior: 1.52,
      roughness: 0.02,
      aspect: 115.2 / 53.31,
      cloud: 1,
      bloom: 0.75,
      exposure: 1.0,
      label: true,
      zoom: 1.1,
      displace: 0,
      dof: true,
      dofFocus: 1,
      dofAperture: 0.9,
    },
  },
  {
    name: 'studio',
    note: 'clean product shot — hard softboxes, crisp specular bars, mid grey',
    set: {
      env: 'studio',
      shell: 'glass',
      fill: 'empty',
      motion: 'turntable',
      speed: 0.35,
      dispersion: 4.2,
      thickness: 0,
      ior: 1.5,
      roughness: 0.01,
      aspect: 115.2 / 53.31,
      cloud: 0,
      bloom: 0.3,
      exposure: 0.9,
      label: true,
      zoom: 1.12,
      displace: 0,
      dof: false,
      dofFocus: 1,
      dofAperture: 0.5,
    },
  },
  {
    name: 'mono',
    note: 'abstract black and white — the only colour is the glass making it',
    set: {
      env: 'mono',
      shell: 'glass',
      fill: 'empty',
      motion: 'float',
      speed: 0.4,
      dispersion: 7.5,
      thickness: 0,
      ior: 1.55,
      roughness: 0.0,
      aspect: 115.2 / 53.31,
      cloud: 0,
      bloom: 0.45,
      exposure: 0.85,
      label: true,
      zoom: 1.12,
      displace: 0,
      dof: true,
      dofFocus: 1,
      dofAperture: 0.7,
    },
  },
  {
    name: 'zebra',
    note: 'hard black-and-white bands — every bend in the surface bends a stripe',
    set: {
      env: 'zebra',
      shell: 'glass',
      fill: 'empty',
      motion: 'turntable',
      speed: 0.3,
      dispersion: 6.0,
      thickness: 0,
      ior: 1.6,
      roughness: 0.0,
      aspect: 115.2 / 53.31,
      cloud: 0,
      bloom: 0.34,
      exposure: 0.72,
      label: true,
      zoom: 1.15,
      displace: 0,
      dof: false,
      dofFocus: 1,
      dofAperture: 0.5,
    },
  },
  {
    // Inverted product shot: same rig as `studio`, exposure floored. Clear glass
    // on black shows you nothing but its edges, so the label and the silhouette
    // carry the whole image.
    name: 'dark studio',
    note: 'inverted product shot — black sweep, glass reduced to its edges',
    set: {
      env: 'darkroom',
      shell: 'glass',
      fill: 'empty',
      motion: 'turntable',
      speed: 0.32,
      dispersion: 5.5,
      thickness: 0,
      ior: 1.52,
      roughness: 0.01,
      aspect: 115.2 / 53.31,
      cloud: 0,
      bloom: 0.55,
      exposure: 1.15,
      label: true,
      zoom: 1.12,
      displace: 0,
      dof: false,
      dofFocus: 1,
      dofAperture: 0.5,
      revealStyle: 'thick',
    },
  },
  {
    // Smoked glass on black. The attenuation colour does the darkening from the
    // INSIDE — tinting the surface would just dull the reflections, whereas
    // attenuation drinks the light on its way through and leaves the rim bright.
    name: 'midnight',
    note: 'smoked glass on black — dark body, bright rim, nothing else',
    set: {
      env: 'noir',
      shell: 'tinted',
      fill: 'empty',
      motion: 'float',
      speed: 0.3,
      dispersion: 6.5,
      thickness: 0,
      ior: 1.6,
      roughness: 0.0,
      aspect: 115.2 / 53.31,
      cloud: 0,
      bloom: 0.8,
      exposure: 1.2,
      label: true,
      zoom: 1.1,
      displace: 0,
      dof: true,
      dofFocus: 1,
      dofAperture: 0.7,
      revealStyle: 'thick',
    },
  },
  {
    name: 'capsule',
    note: 'the original photograph — coral and cream pills packed inside',
    set: {
      env: 'sky',
      shell: 'glass',
      fill: 'pills',
      count: 34,
      itemSize: 1,
      gravity: 5.2,
      motion: 'float',
      speed: 1,
      dispersion: 3.4,
      thickness: 0,
      ior: 1.47,
      roughness: 0.02,
      aspect: 115.2 / 53.31,
      cloud: 1,
      bloom: 0.42,
      exposure: 0.82,
      label: false,
      zoom: 1,
      displace: 0,
      dof: false,
      dofFocus: 1,
      dofAperture: 0.6,
    },
  },
];

export const LOOK_NAMES = LOOKS.map((l) => l.name);

export function findLook(name: string): Look | undefined {
  return LOOKS.find((l) => l.name === name);
}
